:imagesdir: img/

ifndef::rootpath[]
:rootpath: ../../
endif::rootpath[]

ifdef::rootpath[]
:imagesdir: {rootpath}{imagesdir}
endif::rootpath[]



==== PhotoResistor Sensor
[.text-right]
https://github.com/oss-slu/Pi4Micronaut/edit/develop/pi4micronaut-utils/src/docs/asciidoc/components/inputComponents/photoresistorSensor.adoc[Improve this doc]


===== Overview
This section provides the details of the PhotoResistor Sensor, also known as the light sensor, circuit, including its components, assembly instructions, and functionality.

===== Components
* 1 x RaspberryPi
* 1 x Breadboard
* 1 x LED
* 1 x PhotoResistor Sensor
* 1 x 220Ω
* 1 x Capacitor (10µf)
* 2 x 10KΩ
* 4 Jumper Wires
* Power source (appropriate voltage, typically 3.3V or 5V)


===== Assembly Instructions



===== Circuit Diagram


===== Functionality



===== Testing



===== Troubleshooting



===== YAML Configuration
The PhotoResistor as it appears in the YAML file:

[source, yaml]
----
  digital-input:
    photo-resistor-input:                 # <.>
      name: Photo Resistor Input          # <.>
      address: 4                          # <.>
      debounce: 100000                    # <.>
      pull: PULL_DOWN                     # <.>
      provider: pigpio-digital-input      # <.>

----


===== Constructor and Methods
To see the constructor and methods of the PhotoResistorHelper class see our java doc link:https://oss-slu.github.io/Pi4Micronaut/javadoc/com/opensourcewithslu/inputdevices/PhotoResistorHelper.html[here] for more details.


===== Example

====== This controller sets up the photoresistor sensor

[source, java]
----
include::../../../../../../components/src/main/java/com/opensourcewithslu/components/controllers/PhotoResistorController.java[tag=ex]
----