= MicronautPi4J documentation
:stylesheet: style.css
:docinfo: shared
:doctype: book
:title: MicronautPi4J documentation
:toc: left
:toclevels: 4
:sectanchors:
:sectnums:

toc::[]

== Introduction
This is the introduction to the **MicronautPi4J Documentation**!

=== General Information

=== Adding the library to a project

=== Using the Library

=== DigitalInput
To define in application.yaml add digital-input as a field under pi4j, then add each component under digital-input
Each component will need

* name: Name of the component
* address: GPIO pin associated with component
* debounce:
* pull: Either PULL_UP or PULL_DOWN depending on component
* provider: pigpio-digital-input

For digital input components with multiple data pins, such as the rotary encoder, in the application.yaml define
a multi-digital-input field under pi4j and add each multipin component with the following information

* name: Name of the component
* addresses: Comma separated string of address numbers for each pin (i.e. 27, 17, 18)
* debounces: Comma separated list of debounces (i.e. 6000, 500, 500)
* pulls: Comma separated list of pulls (each either PULL_UP or PULL_DOWN)
* initial: The initial state (will be applied to all pins)
* shutdown: The shutdown state (will be applied to all pins)
* provider: pigpio-digital-input (Will be applied to all  pins)

==== Push Button

==== Slide Switch

==== Rotary Encoder

=== DigitalOutput
To define in application.yaml add digital-output as a field under pi4j, then add each component under digital-input
Each component will need

* name: Name of the component
* address: GPIO pin associated with component
* initial: Initial value, either LOW or HIGH
* shutdown: State to take when program successfully shuts down properly, either LOW or HIGH
* provider: pigpio-digital-output

==== LED

=== PWM
To define in application.yaml add digital-input as a field under pi4j, then add each component under digital-input
Each component will need

* name: Name of the component
* address: GPIO pin associated with component
* pwmType: Either SOFTWARE or HARDWARE based upon which type of PWM you wish to use
* provider: pigpio-pwm

==== RGB LED

=== SPI

==== RFID Scanner

=== I2C

==== LCD Screen


== Contributing to the library
