==== Digital Output
[.text-right]
https://github.com/oss-slu/Pi4Micronaut/edit/develop/pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/digitalOutput.adoc[Improve this doc]

"Digital Output" refers to a signal sent from the Raspberry Pi's GPIO pins to another device or circuit. Unlike digital input, which the Raspberry Pi reads, digital output is a signal that the Raspberry Pi sends out.

Digital outputs are also binary, meaning they can only have two states: HIGH (1) or LOW (0). These states correspond to different voltage levels, typically 3.3V for high and 0V (ground) for low on a Raspberry Pi.

To define in application.yaml, add digital-output as a field under Pi4J, then add each component under digital-output.

Each component will need

* name: Name of the component
* address: GPIO pin associated with component
* initial: Initial value, either LOW or HIGH
* shutdown: State to take when program successfully shuts down properly, either LOW or HIGH
* provider: pigpio-digital-output

.Example Digital Output declaration
[source,yaml]
----
include::../../../../../../components/src/main/resources/application.yml[tags=digitalOutput]
----
<1> Component Identifier (Used in @Named annotations)
<2> Component Name
<3> Address of connected GPIO pin
<4> Value to have on shutdown (HIGH = Off, LOW = On)
<5> Value to have on startup
<6> Provider (pigpio-digital-output)