==== PWM
[.text-right]
https://github.com/oss-slu/Pi4Micronaut/edit/develop/pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/pwm.adoc[Improve this doc]

Pulse width modulation, or PWM, is a technique for getting analog results with digital means. Digital control is used to create a square wave, a signal switched between on and off.
This on-off pattern can simulate voltages in between full on (5 Volts) and off (0 Volts) by changing the portion of the time the signal spends on versus the time that the signal spends off.
The duration of “on time” is called the pulse width. To get varying analog values, you change, or modulate, that pulse width (https://learn.sunfounder.com/lesson-2-controlling-led-by-pwm-3/[Source: sunfounder.com]).
In our library, our Active Buzzer component uses PWM. Once fully activated at 5 Volts, the buzzer will go off, creating a tone.

To define in application.yaml add pwm as a field under pi4j, then add each component under pwm.

A BCM numbering system is used. More info can be found https://pinout.xyz[here].

Each component will need:

* name: Name of the component
* BCM address: GPIO pin associated with component
* pwmType: Either SOFTWARE or HARDWARE based upon which type of PWM you wish to use
* provider: pigpio-pwm
* initial: Initial value on startup
* shutdown: Final value at shut down

.Example PWM declaration
[source,yaml]
----
include::../../../../../../components/src/main/resources/application.yml[tags=pwm]
----
<1> Component Identifier (Used in @Named annotations)
<2> Component Name
<3> BCM Address of connected GPIO pin
<4> PWM Type (HARDWARE or SOFTWARE)
<5> Provider (pigpio-digital-output)
<6> Value to have on start up
<7> Value to have on shut down