
==== SPI
[.text-right]
https://github.com/oss-slu/Pi4Micronaut/edit/develop/micronautpi4j-utils/src/docs/asciidoc/components/commun_WithHardware/spi.adoc[Improve this doc]

Serial Peripheral Interface (SPI) is a synchronous serial data protocol used by Microcontrollers for communicating with one or more peripheral devices quickly over short distances. It can also be used for communication between two microcontrollers.

With an SPI connection there is always one Controller device (usually a microcontroller) which controls the peripheral devices. Typically there are three lines common to all the devices:

- Controller In, Peripheral Out (CIPO) - The Peripheral line for sending data to the Controller,

- Controller Out Peripheral In (COPI) - The Controller line for sending data to the Peripherals,

- Serial Clock (SCK) - The clock pulses which synchronize data transmission generated by the Controller, and

- Chip Select pin (CS) - allocated on each device which the Controller can use to enable and disable specific devices and avoid false transmissions due to line noise.

(https://docs.arduino.cc/tutorials/generic/introduction-to-the-serial-peripheral-interface/[Source: docs.arduino.cc])

To define in application.yaml add digital-input as a field under pi4j, then add each component under digital-input. Each component will need:

* name: Name of the component
* address: Address for Controller/Peripheral
* baud: Baud rate/data rate
* reset-pin: Address of GPIO reset pin

[source,yaml]
----
include::../../../../../../components/src/main/resources/application.yml[tags=spi]
----
<1> Component Identifier (Used in @Named annotations)
<2> Component Name
<3> TO DO: Figure out what this address is
<4> Baud rate
<5> Address of GPIO Reset pin

