
==== SPI
[.text-right]
https://github.com/oss-slu/Pi4Micronaut/edit/develop/pi4micronaut-utils/src/docs/asciidoc/components/commun_WithHardware/spi.adoc[Improve this doc]

The Serial Peripheral Interface (SPI) is a communication protocol used to transfer data between the Raspberry Pi and peripheral devices. These peripheral devices may be either sensors or actuators.

(https://raspberrypi-aa.github.io/session3/spi.html[Source: raspberrypi-aa.github.io])

Many different devices use the SPI protocol, such as SD card reader modules, RFID card reader modules, and 2.4 GHz wireless transmitter/receivers all use SPI to communicate with the Raspberry Pi.

(https://www.circuitbasics.com/basics-of-the-spi-communication-protocol/[Source: circuitbasics.com])


SPI uses 4 separate connections to communicate with the target device:

- COPI (Controller Output/Peripheral Input) – Line for the Controller to send data to the Peripherals.

- CIPO (Controller Input/Peripheral Output) – Line for the Peripherals to send data to the Controller.

- SCLK (Clock) – Line for the clock signal.

- PS/CS (Peripheral Select/Chip Select) – Line for the Controller to select which Peripheral to send data to.


====
*Note:* Controller/Peripheral is formerly referred to as Master/Slave. In order to move away from the use of such terminology, we have opted to use the term Controller in place of Master, and Peripheral in place of Slave.
====

A BCM numbering system is used. More info can be found https://pinout.xyz[here].

To define in application.yaml add spi as a field under pi4j, then add each component under spi.

Each component will need:

* name: Name of the component
* BCM address: Address for Controller/Peripheral
* baud: Baud rate/data rate
* reset-pin: Address of GPIO reset pin

.Example SPI declaration
[source,yaml]
----
include::../../../../../../components/src/main/resources/application.yml[tags=spi]
----
<1> Component Identifier (Used in @Named annotations)
<2> Component Name
<3> BCM Address of GPIO Reset pin
<4> Baud rate

