micronaut:
  application:
    name: home_Automation
netty:
  default:
    allocator:
      max-order: 3

pi4j:
  # tag::i2c[]
  i2c:
    lcd:                                  # <1>
      name: lcd                           # <2>
      bus: 1                              # <3>
      device: 0x27                        # <4>
  # end::i2c[]

  # tag::digitalInput[]
  digital-input:
    pir-sensor-1:
      name: PIR Sensor
      address: 12
      pull: PULL_DOWN
      debounce: 30000
      provider: pigpio-digital-input
    pir-sensor-2:
      name: PIR Sensor
      address: 16
      pull: PULL_DOWN
      debounce: 30000
      provider: pigpio-digital-input
  # end::digitalInput[]

  # tag::multipwm[]
  multi-pwm:
    rgb-led:                                    # <.>
      name: RGB LED                             # <.>
      addresses: 17, 18, 27                     # <.>
      pwmTypes: SOFTWARE, SOFTWARE, SOFTWARE    # <.>
      provider: pigpio-pwm                      # <.>
      initials: 0, 0, 0                         # <.>
      shutdowns: 0, 0, 0                        # <.>
  # end::multipwm[]