=== How to Create a New Component
[.text-right] 
https://github.com/oss-slu/Pi4Micronaut/edit/develop/micronautpi4j-utils/src/docs/asciidoc/contribute/newComponent.adoc[Improve this doc]

TODO: add info on how to add a new component

NOTE: helper and controller are just micronaut framework practices, might not need to include exact details, may just reference a user to the micronaut documentation. 

* controller
** controls the component
** `components\src\main\java\com\opensourcewithslu\components\controllers`

include::exampleController.java[tag=ex]


* helper
** where all the actions are defined. 
** `micronautpi4j-utils\src\main\java\com\opensourcewithslu`


* input versus output device
** input devices main task is taking in information
*** `micronautpi4j-utils\src\main\java\com\opensourcewithslu\inputdevices`
** output devices display or output information
*** `micronautpi4j-utils\src\main\java\com\opensourcewithslu\outputdevices`





## Adding components to the application yml

TODO: explain the purpose of the yml file and what parameters each component will need to have, it will presumably be different for each component type. 

Each component will need to be added to the application yml found at `components\src\main\resources\application.yml`.  