name: Build and Release Library
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Change wrapper permissions
      run: chmod +x pi4micronaut-utils/gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: pi4micronaut-utils/
    - name: Execute Gradle build
      working-directory: pi4micronaut-utils
      run: ./gradlew shadowJar
  publish-jar:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      needs: build-library
      steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x pi4micronaut-utils/gradlew
      - name: Set up GPG key
        run: |
          echo "${{ secrets.GPG_KEY }}" | base64 --decode | gpg --import
          echo "${{ secrets.GPG_PASSWORD }}" | gpg --passphrase-fd 0 --batch --yes --pinentry-mode loopback -a --export-secret-keys | gpg --import
        env:
          GPG_TTY: /dev/tty

      - name: Publish Library
        working-directory: pi4micronaut-utils
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
        run: ./gradlew publish
