name: Build Adocs and Javadocs

on:
  push:
    branches:
    - main
    - develop

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Build Adocs and Javadocs
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: tonynv/asciidoctor-action@master
      with:
          program: "./gradlew asciidoctor javadoc"

    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./pi4micronaut-utils/build/docs/asciidoc/

