name: Publish Documentation
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  publish-asciidoc:
    uses: ./.github/workflows/asciidoc-publish.yml
    secrets:
      ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}

  publish-javadoc:
    needs: publish-asciidoc
    uses: ./.github/workflows/javadoc-gh-pages.yml
