name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  publish-asciidoc:
    uses: ./.github/workflows/asciidoc-publish.yml

  publish-javadoc:
    needs: publish-asciidoc
    uses: ./.github/workflows/javadoc-gh-pages.yml
